name: Blacksmith
author: aPunch, jrbudda, HurricanKai
version: 1.12
main: net.apunch.blacksmith.BlacksmithPlugin
depend: [Citizens, Vault]
softdepend: [HyperConomy]

commands:
  bs:
    permission: blacksmith
    description: Blacksmith base Command