name: Blacksmith
author: aPunch, jrbudda, HurricanKai
version: 1.12
main: net.apunch.blacksmith.BlacksmithPlugin
depend: [Citizens, Vault]
softdepend: [HyperConomy]

commands:
  bs:
    description: The Blacksmith base command
    usage: /bs <mode> <mode.node>
    permission: bs
    permission-message: You dont have the bs Permission
  blacksmith:
    usage: /backsmith givegems <player> <amount>
permissions:
   bs.reload:
     description: Allows you to Reload bs
     default: op
   bs.reset:
     description: Allows you to reset bs
     default: op